version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
